### ISSUE TITLE
same file not select second time

### ISSUE THREAD

**Issue by arpita0408** [MihirHundiwala/image-cropper-in-vue#1]
Hello,
i am facing issue after file cropping and when we cancel file from modal pop-up.

1. Once file get cropped , for the same file modal pop-up is not loading.
2. When we click on "cancel" from pop-up,  2nd time file cannot be selected.

what do i need to do ? is it issue regarding reset file value null? or something else.
Please suggest me.

**Comment by MihirHundiwala** [comment]
Hi, Yes you are correct input field needs to be reset, I have made the changes, take a look at latest commit changes, thanks

I have also made slight changes in variable names for convenience and some styling
